driver:
  name: docker
  use_sudo: false
  links:
    - dev-vault:dev-vault
  # dockerfile: test/dockerfile

provisioner:
  name: chef_zero
  client_rb:
    chef_license: "accept-silent"
  deprecations_as_errors: false

platforms:
  - name: centos
  - name: debian
  - name: ubuntu

suites:
  - name: default
    attributes:
      token: <%= ENV['VAULT_TOKEN'] %>
    run_list:
      - recipe[test::default]