driver:
  name: docker
  use_sudo: false
  links:
    - dev-vault:dev-vault
  run_options:
    net: bridge
  # dockerfile: test/dockerfile

# Preparing for Chef 13
client_rb:
  treat_deprecation_warnings_as_errors: true
  resource_cloning: false

platforms:
  - name: debian-9.2
  - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[test::default]
    attributes:
      vault_certificate:
        address: 'http://dev-vault:8200/'
        token: <%= ENV['VAULT_ROOT_TOKEN'] %>
        pki_role: 'example-com'