sudo: required

services:
  - docker

language: ruby
cache: bundler

before_script:
  - VAULT_CONTAINER_ID=`docker run -e SKIP_SETCAP=true --cap-add IPC_LOCK -d --name=dev-vault -p 8200:8200 vault`
  - sleep 2 # Allow the container to fully initialize
  - VAULT_ROOT_TOKEN=`docker logs $VAULT_CONTAINER_ID | grep -Po "(?<=Root Token. )([^\n]+)"`
  - export VAULT_ROOT_TOKEN
 # Mount the secret and pki backends
 # Populate vault with some data
  
script:
  - echo "Root Token = $VAULT_ROOT_TOKEN"
  - bundle show foodcritic
  - bundle exec foodcritic -f any .
  - bundle exec cookstyle -D
  - bundle exec kitchen converge all
