sudo: required
dist: trusty

services:
  - docker

language: ruby

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

install: echo "skip bundle install"

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - VAULT_CONTAINER_ID=`docker run -e SKIP_SETCAP=true --cap-add IPC_LOCK -d --name=dev-vault -p 8200:8200 vault`
  - sleep 2 # Allow the container to fully initialize
  - |
    VAULT_ROOT_TOKEN=`docker logs $VAULT_CONTAINER_ID | grep -Po "(?<=Root Token: )([^\n]+)"`
  - export VAULT_ROOT_TOKEN
 # Mount the secret and pki backends
 # Populate vault with some data
  
script:
  - echo "Root Token = $VAULT_ROOT_TOKEN"
  - foodcritic -f any .
  - cookstyle -D
  - kitchen converge all
