sudo: required

services:
  - docker

language: ruby

rvm:
  - 2.4
 
before_install:
  - docker pull vault
 
before_script:
  - |
    docker run -e SKIP_SETCAP=true --cap-add IPC_LOCK -d --name=dev-vault -p 8200:8200 vault
  - VAULT_CONTAINER_ID=`docker inspect --format="{{.Id}}" dev-vault`
  - echo $VAULT_CONTAINER_ID
  - sleep 15
  - docker logs $VAULT_CONTAINER_ID
  - VAULT_ROOT_TOKEN=`docker logs $VAULT_CONTAINER_ID | grep -Po "(?<=Root Token. )([^\n]+)"`
 #- VAULT_ROOT_TOKEN=`docker logs $(docker inspect --format="{{.Id}}" dev-vault) | grep -Po "(?<=Root Token. )([^\n]+)"`
  - export VAULT_ROOT_TOKEN
 # Mount the secret and pki backends
 # Populate vault with some data
  
script:
  - echo "Container ID = $VAULT_CONTAINER_ID"
  - echo "Root Token = $VAULT_ROOT_TOKEN"
  - foodcritic -f any .
  - cookstyle -D
  - kitchen converge all
